baseURL = "/"
languageCode = "it-IT"
defaultContentLanguage = "it"
title = "Eventi Biella"
theme = "eventi"
googleAnalytics = "UA-146395434-1"

[permalinks]
  posts = "/:filename/"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Contatti"
    url = "/contact/"
    weight = 2

[params]
  author = "Admin"
  dateFormat = "Jan 2, 2006"
  description = "Eventi Biella è un sito dall'interfaccia semplice e intuitiva nato con lo scopo di racchiudere in un unico luogo tutti gli eventi presenti nel biellese e con la possibilità di poter promuovere un proprio evento."
  image = "/img/biglogo.png"


