baseURL = "/"
languageCode = "it-IT"
defaultContentLanguage = "it"
title = "Eventi Biella"
theme = "eventi"

enableRobotsTXT = true
canonifyURLs = true

[permalinks]
  posts = "/:filename/"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Contatti"
    url = "/contact/"
    weight = 2

[params]
  author = "Admin"
  dateFormat = "Jan 2, 2006"
  description = "Eventi Biella è un sito dall'interfaccia semplice e intuitiva nato con lo scopo di racchiudere in un unico luogo tutti gli eventi presenti nel biellese."
  logo = "img/biglogo.png"
  googleAnalytics = "UA-146395434-1"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

